
export const alphabets = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];

export const EXPLORE_BY = [
 'Nutrition ','Public Health','Mental Health','Fitness',
]

export const TODAY_TOP_STORIES = [
  {id: 1, image: '/img1.jpg', title: 'Exercises for Chronic Pain Management'},
  {id: 2, image: '/img2.jpg', title: 'The Link Between Sleep and Mental Health: Rest Well, Feel Well'},
]

export const TOP_ARTICLES = [
  {id: 1, image: '/img3.png', title: 'The Impact of Sedentary Lifestyleon Cardiovascular Health'},
  {id: 2, image: '/img4.jpg', title: 'Injury Prevention Strategies For Athletes'},
  {id: 3, image: '/img5.jpg', title: 'Prioritizing  Mental Health'},
]

export const TOP_HEALTH_TOPICS = [
  'Cancer','Alzheimers','Athlete’s Foot','Eczema','ADHD','Schizophrenia','Mental Health','Arthritis','Hypertension','Sleep Disorder','Diabetes'
 ]
 
 export const FEATURED_STORIES = [
  {id: 1, image: '/img7.png', topic: 'Mental Health', title: 'Managing Stress and Anxiety: Practical Tips for a Calmer Mind'},
  {id: 2, image: '/img6.png', topic: 'Public Health', title: 'The Role of Vaccination in Preventing Infectious Diseases'},
  {id: 3, image: '/img8.png', topic: 'Nutrition', title: 'The Role of Nutrition in Disease Prevention: Eat Right, Live Right'},
]

export const aboutList = [
  {id: 1, text: 'Credible, up-to-date health information.', img: '/safe.png'},
  {id: 2, text: 'Complete Transparency.', img: '/eye.png'},
]

export const MORE_ARTICLES = [
  {id: 1, image: '/img9.png', title: 'Water Quality and Public Health', desc: 'Unfortunately, access to clean water is still a significant challenge in many parts of the world, and it poses health risks'},
  {id: 2, image: '/img10.png', title: 'The Rising Threat of Antibiotic Resistance', desc: 'Explore the impact on healthcare, implications of antibiotic resistance and strategies to preserve it’s effectiveness.'},
]

export const HEALTH_TOPICS = [
  // A
  "Abdominal pain",
  "Acne",
  "Addiction",
  "Adenoids",
  "Adrenal disorders",
  "Aging",
  "Alcoholism",
  "Allergies",
  "Alzheimer's disease",
  "Amnesia",
  "Anemia",
  "Angina",
  "Ankle injuries",
  "Anorexia nervosa",
  "Antibiotics",
  "Anxiety disorders",
  "Appendicitis",
  "Arthritis",
  "Asthma",
  "Atherosclerosis",
  "Athlete's foot",
  "Atrial fibrillation",
  "Autoimmune diseases",
  "Autism spectrum disorder",
  "Ayurveda",

  // B
  "Back pain",
  "Bacterial infections",
  "Balance disorders",
  "Bariatric surgery",
  "Barrett's esophagus",
  "Basal cell carcinoma",
  "Bedwetting",
  "Bell's palsy",
  "Benign prostatic hyperplasia",
  "Bile duct disorders",
  "Binge eating disorder",
  "Bipolar disorder",
  "Birth control",
  "Bladder cancer",
  "Bleeding disorders",
  "Blood clots",
  "Bone cancer",
  "Bone density",
  "Bowel obstruction",
  "Brain injury",
  "Breast cancer",
  "Bronchitis",
  "Bulimia nervosa",
  "Burns",
  "Bursitis",

  // C
  "Cancer",
  "Candidiasis",
  "Cardiac arrest",
  "Cardiomyopathy",
  "Carpal tunnel syndrome",
  "Cataracts",
  "Celiac disease",
  "Cerebral palsy",
  "Cervical cancer",
  "Chemotherapy",
  "Chest pain",
  "Childhood obesity",
  "Chlamydia",
  "Cholesterol",
  "Chronic fatigue syndrome",
  "Chronic kidney disease",
  "Cirrhosis",
  "Cognitive behavioral therapy",
  "Cold sores",
  "Colitis",
  "Colon cancer",
  "Concussion",
  "Conjunctivitis",
  "Constipation",
  "COPD (Chronic obstructive pulmonary disease)",

  // D
  "Dandruff",
  "Deep vein thrombosis",
  "Dehydration",
  "Dementia",
  "Dental health",
  "Depression",
  "Dermatitis",
  "Diabetes",
  "Diarrhea",
  "Dietary supplements",
  "Digestive disorders",
  "Dislocations",
  "Diverticulitis",
  "Dizziness",
  "Down syndrome",
  "Dry eye syndrome",
  "Dyslexia",
  "Dysphagia",
  "Dystonia",
  "Dysmenorrhea",
  "Dental implants",
  "Drug addiction",
  "Dupuytren's contracture",
  "Dwarfism",
  "Dyspepsia",

  // E
  "Ear infections",
  "Eating disorders",
  "Ebola",
  "Eczema",
  "Edema",
  "Electrocardiogram",
  "Embolism",
  "Emphysema",
  "Endometriosis",
  "Epilepsy",
  "Erectile dysfunction",
  "Esophageal cancer",
  "Essential tremor",
  "Exercise physiology",
  "Eye floaters",
  "Endoscopy",
  "Epidemiology",
  "Erysipelas",
  "Euthanasia",
  "Exocrine pancreatic insufficiency",
  "Eye strain",
  "Ehlers-Danlos syndrome",
  "Encephalitis",
  "Ergonomics",
  "Esophagitis",

  // F
  "Fatigue",
  "Fever",
  "Fibromyalgia",
  "Flu (Influenza)",
  "Food allergies",
  "Food poisoning",
  "Foot ulcers",
  "Fractures",
  "Frostbite",
  "Fungal infections",
  "Fatty liver disease",
  "Fertility",
  "Fetal alcohol syndrome",
  "Fibroids",
  "Fistulas",
  "Flatulence",
  "Flesh-eating disease",
  "Floaters",
  "Folliculitis",
  "Foodborne illness",
  "Fragile X syndrome",
  "Frostnip",
  "Frozen shoulder",
  "Functional medicine",
  "Fusobacterium infections",

  // G
  "Gallbladder disease",
  "Gallstones",
  "Gangrene",
  "Gastritis",
  "Gastroenteritis",
  "Gastroesophageal reflux disease (GERD)",
  "Generalized anxiety disorder",
  "Genetic disorders",
  "Genital herpes",
  "Giardiasis",
  "Gingivitis",
  "Glaucoma",
  "Gluten intolerance",
  "Goiter",
  "Gonorrhea",
  "Gout",
  "Graves' disease",
  "Growth disorders",
  "Guillain-Barré syndrome",
  "Gum disease",
  "Gynecological disorders",
  "Gallbladder cancer",
  "Gastroparesis",
  "Gestational diabetes",
  "Glomerulonephritis",

  // H
  "Hair loss",
  "Hand-foot-and-mouth disease",
  "Hangover",
  "Hashimoto's thyroiditis",
  "Head lice",
  "Headaches",
  "Hearing loss",
  "Heart attack",
  "Heartburn",
  "Heatstroke",
  "Hemochromatosis",
  "Hemophilia",
  "Hemorrhoids",
  "Hepatitis",
  "Hernia",
  "Herpes",
  "Hiccups",
  "High blood pressure",
  "Hip replacement",
  "Hives",
  "Hodgkin's lymphoma",
  "Hormone therapy",
  "Huntington's disease",
  "Hydrocephalus",
  "Hyperthyroidism",

  // I
  "Immune system disorders",
  "Immunotherapy",
  "Impetigo",
  "Incontinence",
  "Indigestion",
  "Infertility",
  "Influenza",
  "Ingrown toenails",
  "Insomnia",
  "Insulin resistance",
  "Interstitial cystitis",
  "Intestinal obstruction",
  "Intrauterine growth restriction",
  "Iron deficiency anemia",
  "Irritable bowel syndrome",
  "Itching",
  "IV therapy",
  "Ichthyosis",
  "Idiopathic pulmonary fibrosis",
  "Impingement syndrome",
  "Infectious diseases",
  "Inflammatory bowel disease",
  "Inguinal hernia",
  "Intraocular pressure",
  "Ischemic stroke",

  // J
  "Jaundice",
  "Jet lag",
  "Joint pain",
  "Juvenile arthritis",
  "Jaw pain",
  "Jock itch",
  "Juvenile diabetes",
  "Joint replacement",
  "Jungle fever",
  "Janus kinase inhibitors",
  "Juvenile idiopathic arthritis",
  "Jellyfish stings",
  "Joint dislocation",
  "Juvenile dermatomyositis",
  "Juvenile osteoporosis",
  "Jaw surgery",
  "Juvenile myoclonic epilepsy",
  "Joint stiffness",
  "Jumping Frenchmen of Maine",
  "Juvenile polyposis syndrome",
  "Joint hypermobility",
  "Juvenile glaucoma",
  "Jaw fractures",
  "Juvenile fibromyalgia",
  "Joint infections",

  // K
  "Kidney cancer",
  "Kidney failure",
  "Kidney stones",
  "Knee injuries",
  "Knee replacement",
  "Korsakoff syndrome",
  "Kyphosis",
  "Kaposi's sarcoma",
  "Kawasaki disease",
  "Keloids",
  "Keratitis",
  "Kernicterus",
  "Ketogenic diet",
  "Kidney transplant",
  "Klinefelter syndrome",
  "Klippel-Feil syndrome",
  "Knee arthritis",
  "Keratoconus",
  "Kidney infections",
  "Krabbe disease",
  "Knee ligament injuries",
  "Klebsiella infections",
  "Knock knees",
  "Keratosis pilaris",
  "Kwashiorkor",

  // L
  "Lactose intolerance",
  "Laparoscopy",
  "Laryngeal cancer",
  "Laryngitis",
  "Laser eye surgery",
  "Leg cramps",
  "Leishmaniasis",
  "Leukemia",
  "Lice",
  "Lichen planus",
  "Lipoma",
  "Liver cancer",
  "Liver disease",
  "Low blood sugar",
  "Lung cancer",
  "Lupus",
  "Lyme disease",
  "Lymphoma",
  "Lactation",
  "Leg ulcers",
  "Leprosy",
  "Lipid disorders",
  "Listeriosis",
  "Low testosterone",
  "Lumbar pain",

  // M
  "Macular degeneration",
  "Malaria",
  "Mammography",
  "Manic depression",
  "Measles",
  "Melanoma",
  "Meningitis",
  "Menopause",
  "Mental health",
  "Metabolic syndrome",
  "Migraine",
  "Miscarriage",
  "Mitral valve prolapse",
  "Mononucleosis",
  "Motion sickness",
  "Multiple sclerosis",
  "Mumps",
  "Muscle cramps",
  "Muscular dystrophy",
  "Myasthenia gravis",
  "Myocardial infarction",
  "Myopia",
  "Meditation",
  "Menstrual disorders",
  "Microbiome health",

  // N
  "Narcolepsy",
  "Nasal polyps",
  "Nausea",
  "Neck pain",
  "Neonatal care",
  "Nephritis",
  "Neuralgia",
  "Neuroblastoma",
  "Neuropathy",
  "Night sweats",
  "Non-Hodgkin's lymphoma",
  "Norovirus",
  "Nutrition",
  "Nosebleeds",
  "Nail fungus",
  "Narcotic addiction",
  "Neonatal jaundice",
  "Nephrotic syndrome",
  "Neurofibromatosis",
  "Nicotine dependence",
  "Nystagmus",
  "Nutrient deficiencies",
  "Nasal congestion",
  "Neuritis",
  "Nocturia",

  // O
  "Obesity",
  "Obsessive-compulsive disorder",
  "Occupational therapy",
  "Ocular hypertension",
  "Oncology",
  "Opioid addiction",
  "Oral cancer",
  "Organ transplant",
  "Orthodontics",
  "Osteoarthritis",
  "Osteoporosis",
  "Otitis media",
  "Ovarian cancer",
  "Overactive bladder",
  "Oxygen therapy",
  "Ozone therapy",
  "Onychomycosis",
  "Obstructive sleep apnea",
  "Ocular migraines",
  "Oral hygiene",
  "Orthopedic surgery",
  "Ovarian cysts",
  "Oxidative stress",
  "Osgood-Schlatter disease",
  "Ototoxicity",

  // P
  "Pancreatic cancer",
  "Panic disorder",
  "Paralysis",
  "Parkinson's disease",
  "Peptic ulcer",
  "Periodontitis",
  "Peripheral artery disease",
  "Pharyngitis",
  "Phobias",
  "Physical therapy",
  "Piles (Hemorrhoids)",
  "Pneumonia",
  "Polio",
  "Postpartum depression",
  "Pregnancy",
  "Prostate cancer",
  "Psoriasis",
  "Psychotherapy",
  "Pulmonary embolism",
  "Plantar fasciitis",
  "Post-traumatic stress disorder",
  "Pre-eclampsia",
  "Probiotics",
  "Porphyria",
  "Polycystic ovary syndrome",

  // Q
  "Q fever",
  "Quadriceps injuries",
  "Quarantine health",
  "Quinsy",
  "Quadrantanopia",
  "Quantitative sensory testing",
  "Quercetin benefits",
  "Queasy stomach",
  "Quick-relief inhalers",
  "Quinolone antibiotics",
  "Quadriplegia",
  "Quitting smoking",
  "Quality of life",
  "Quell pain",
  "Quasi-static exercise",
  "Quincke's edema",
  "Quadratus lumborum pain",
  "Quinine side effects",
  "Quasi-infectious diseases",
  "Quantitative electroencephalography",
  "Quail egg allergies",
  "Quartz crystal therapy",
  "Quell nausea",
  "Quadriceps tendonitis",
  "Quiet sleep disorders",

  // R
  "Rabies",
  "Radiation therapy",
  "Rash",
  "Raynaud's disease",
  "Rehabilitation",
  "Renal failure",
  "Respiratory infections",
  "Restless legs syndrome",
  "Rheumatoid arthritis",
  "Rickets",
  "Ringworm",
  "Rosacea",
  "Rotator cuff injuries",
  "Rubella",
  "Runner's knee",
  "Radiology",
  "Rectal cancer",
  "Reflux",
  "Reiki",
  "Respiratory therapy",
  "Retinal detachment",
  "Rhabdomyolysis",
  "Rhinitis",
  "Root canal",
  "Rotavirus",

  // S
  "Salmonella",
  "Sarcoidosis",
  "Schizophrenia",
  "Sciatica",
  "Scoliosis",
  "Seasonal affective disorder",
  "Seizures",
  "Sepsis",
  "Sexually transmitted infections",
  "Shingles",
  "Sickle cell anemia",
  "Sinusitis",
  "Skin cancer",
  "Sleep apnea",
  "Smoking cessation",
  "Snoring",
  "Sore throat",
  "Spinal cord injury",
  "Sprains",
  "Stress management",
  "Stroke",
  "Stuttering",
  "Substance abuse",
  "Sunburn",
  "Systemic lupus erythematosus",

  // T
  "Tachycardia",
  "Tendinitis",
  "Testicular cancer",
  "Tetanus",
  "Thalassemia",
  "Throat cancer",
  "Thrombosis",
  "Thyroid cancer",
  "Tinnitus",
  "Tonsillitis",
  "Tooth decay",
  "Tourette syndrome",
  "Toxic shock syndrome",
  "Transient ischemic attack",
  "Trichomoniasis",
  "Tuberculosis",
  "Type 1 diabetes",
  "Type 2 diabetes",
  "Typhoid fever",
  "Tai chi",
  "Temporomandibular joint disorders",
  "Testosterone therapy",
  "Thoracic outlet syndrome",
  "Tick-borne diseases",
  "Trigeminal neuralgia",

  // U
  "Ulcerative colitis",
  "Ulcers",
  "Underactive thyroid",
  "Upper respiratory infections",
  "Ureteral cancer",
  "Urinary incontinence",
  "Urinary tract infections",
  "Uterine cancer",
  "Uveitis",
  "Ultrasound therapy",
  "Ulnar nerve entrapment",
  "Umbilical hernia",
  "Undernutrition",
  "Upper back pain",
  "Uric acid",
  "Urticaria",
  "Uterine fibroids",
  "Ultraviolet therapy",
  "Uncontrolled hypertension",
  "Urologic diseases",
  "Urea cycle disorders",
  "Urethritis",
  "Ulcerative keratitis",
  "Unintentional weight loss",
  "Upper limb disorders",

  // V
  "Vaginal infections",
  "Varicose veins",
  "Vascular dementia",
  "Vasculitis",
  "Vertigo",
  "Viral hepatitis",
  "Viral infections",
  "Vision therapy",
  "Vitamin deficiencies",
  "Vocal cord disorders",
  "Vulvar cancer",
  "Vaccinations",
  "Venous insufficiency",
  "Ventricular fibrillation",
  "Vestibular disorders",
  "Vibrio infections",
  "Viral meningitis",
  "Vitamin D deficiency",
  "Vulvodynia",
  "Vagus nerve stimulation",
  "Valley fever",
  "Ventricular tachycardia",
  "Visual impairment",
  "Vitreous hemorrhage",
  "Voice therapy",

  // W
  "Warts",
  "Weight loss",
  "West Nile virus",
  "Whiplash",
  "Whooping cough",
  "Wilson's disease",
  "Women's health",
  "Wound care",
  "Wrist pain",
  "Waterborne diseases",
  "Weak immune system",
  "Weight gain",
  "Wheezing",
  "White blood cell disorders",
  "Wisdom teeth",
  "Wolff-Parkinson-White syndrome",
  "Workplace ergonomics",
  "Wrinkles",
  "Wrist fractures",
  "Wellness coaching",
  "Whipple's disease",
  "Worm infections",
  "Waist pain",
  "Water retention",
  "Wrist tendonitis",

  // X
  "X-linked agammaglobulinemia",
  "Xeroderma pigmentosum",
  "X-ray imaging",
  "Xanthoma",
  "Xerophthalmia",
  "X-linked hypophosphatemia",
  "X-chromosome disorders",
  "Xerosis",
  "X-linked ichthyosis",
  "Xylitol benefits",
  "X-linked adrenoleukodystrophy",
  "Xerostomia",
  "X-linked mental retardation",
  "Xanthogranuloma",
  "X-linked sideroblastic anemia",
  "Xerophagia",
  "X-linked dystonia-parkinsonism",
  "X-ray therapy",
  "X-linked retinoschisis",
  "Xanthine oxidase inhibitors",
  "X-linked lymphoproliferative disease",
  "Xeromammography",
  "X-linked myotubular myopathy",
  "Xanthophyll supplements",
  "X-linked hyper-IgM syndrome",

  // Y
  "Yeast infections",
  "Yellow fever",
  "Yoga therapy",
  "Yersinia infections",
  "Yawn reflex",
  "Youth mental health",
  "Y-linked disorders",
  "Yeast allergy",
  "Yellow nail syndrome",
  "Yersiniosis",
  "Youth obesity",
  "Yohimbine side effects",
  "Yoga for back pain",
  "Y-chromosome infertility",
  "Youth depression",
  "Yeast overgrowth",
  "Yellow jacket stings",
  "Yersinia pestis",
  "Youth anxiety",
  "Yoga for stress",
  "Yttrium therapy",
  "Youth eating disorders",
  "Yellow skin disorders",
  "Yogic breathing",
  "Youth sleep disorders",

  // Z
  "Zika virus",
  "Zinc deficiency",
  "Zollinger-Ellison syndrome",
  "Zoonotic diseases",
  "Zygomatic fractures",
  "Zinc supplementation",
  "Zoster (Shingles)",
  "Zero-gravity therapy",
  "Zygomycosis",
  "Zinc oxide benefits",
  "Zolpidem side effects",
  "Zoonosis prevention",
  "Zinc absorption",
  "Zygomatic arch pain",
  "Zoster sine herpete",
  "Zinc toxicity",
  "Zolmitriptan therapy",
  "Zoonotic bacterial infections",
  "Zygote development",
  "Zinc finger proteins",
  "Zoster ophthalmicus",
  "Zinc lozenges",
  "Zoonotic viral infections",
  "Zygomycete infections",
  "Z-drugs for insomnia"
];

export const PRODUCTS = [
   {name: 'Gogo Cleanser', 
    desc:'Browse our vast range of health conditions and find informationon treatment, prevention and coping strategies and stories.',
    overview: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,`
Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,`
Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`,],
    usage: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,`
Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,`
Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
    ingredients: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,
`Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,
`Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
    pricing: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
  and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,
  `Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,
  `Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
  keywords: ['Hair loss', 'Minoxydl', 'Creatine'],
  sources: [], updateHistory: [],
  publishedOn: 'November 9, 2024',
  updatedOn: 'December 10, 2024',
  author: 'Kalu Daniel'
},
{name: 'Yoyo bitters', 
  desc:'Browse our vast range of health conditions and find informationon treatment, prevention and coping strategies and stories.',
  overview: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,`
Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,`
Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`,],
  usage: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,`
Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,`
Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
  ingredients: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,
`Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,
`Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
  pricing: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,
`Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,
`Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
keywords: ['Hair loss', 'Minoxydl', 'Creatine'],
sources: [], updateHistory: [],
publishedOn: 'November 9, 2024',
updatedOn: 'December 10, 2024',
author: 'Kalu Daniel'
},
{name: 'Andrew Liver Salt', 
  desc:'Browse our vast range of health conditions and find informationon treatment, prevention and coping strategies and stories.',
  overview: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,`
Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,`
Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`,],
  usage: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,`
Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,`
Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
  ingredients: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,
`Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,
`Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
  pricing: [`Hair loss (alopecia) can affect just your scalp or your entire body, 
and it can be temporary or permanent. It can be the result of heredity, hormonal changes, medical conditions or a normal part of aging. Anyone can lose hair on their head, but it's more common in men.`,
`Baldness typically refers to excessive hair loss from your scalp. Hereditary hair loss with age is the most common cause of baldness. Some people prefer to let their hair loss run its course untreated and unhidden. Others may cover it up with hairstyles, makeup, hats or scarves. And still others choose one of the treatments available to prevent further hair loss or restore growth.`,
`Before pursuing hair loss treatment, talk with your doctor about the cause of your hair loss and treatment options.`],
keywords: ['Hair loss', 'Minoxydl', 'Creatine'],
sources: [], updateHistory: [],
publishedOn: 'November 9, 2024',
updatedOn: 'December 10, 2024',
author: 'Kalu Daniel'
},
]